<?php
//
// ETS2MP Homepage language file.
// File:				slovene.php
// Language name: 		Slovene
// Translated name: 	Slovenščina
//

$_lang["download"] = "Prenesi";
$_lang["home"] = "Domov";
$_lang["status"] = "Status strežnikov";
$_lang["username"] = "Uporabniško ime";
$_lang["password"] = "Geslo";
$_lang["login"] = "Vpis";
$_lang["register"] = "Registracija";
$_lang["download.latest.version"] = "Prenesi najnovejšo verzijo";
$_lang["current.release"] = "Trenutna verzija:";
$_lang["language"] = "Jezik";
$_lang["join"] = "PRIDRUŽI SE";
$_lang["mainpage.join"] = "Pridružite se na tisoče oboževalcev tovornjakov in igrajte preko spleta!";
$_lang["ts3.advertisement"] = "Glasovna interakcija z drugimi igralci - kliknite in se pridružite TS3 strežniku.";
$_lang["facebook.advertisement"] = "Najnovejše novice na naši Facebook strani.";
$_lang["registration.blocked"] = "Registracija je blokirana - delamo na novih funkcijah, zato smo bili prisiljeni začasno onemogočiti registracijo. Ponovno bo odklenjena, ko bo nova verzija na voljo za prenos.";
$_lang["invalid.username.password"] = "Neveljaven e-naslov ali geslo.";
$_lang["already.logged"] = "Uporabnik je že prijavljen.";
$_lang["welcome"] = "Dobrodošli";
$_lang["logout"] = "Izpis";
$_lang["bans"] = "Bani";
$_lang["version"] = "Verzija";
$_lang["update.time"] = "Čas posodobitve";
$_lang["req.game.version"] = "Potrebna verzija igre";
$_lang["requires"] = "Potrebuje";
$_lang["or.newer"] = "ali novejše";
$_lang["game.client"] = "Game Client";
$_lang["download.no.permissions"] = "Za prenos se prijavite.";
$_lang["why.create.account"] = "Zakaj ustvariti račun?<br />En račun bo uporabljen za privajo v vse storitve (forum, igra, gospodarstvo in druge). Načrtujemo njihovo uporabo za uvedbo on-line gospodarstva in osebno statistiko voznikov. Lahko boste spreminjali vaš profil.";
$_lang["website.title"] = "ETS2MP - Virtualni tovornjakarsi svet - večigralska modifikacija za igro Euro Truck Simulator 2 podjetja SCS Software";
$_lang["cookies.warning"] = "Ta stran uporablja <a href=\"http://sl.wikipedia.org/wiki/Piškotek\">piškotke</a>. Če boste nadaljevali z brskanjem po spletnem mestu, se strinjate z uporabo piškotkov.";
$_lang["forum"] = "Forum";
$_lang["cannot.create.account.when.logged"] = "Ustvarjanje novega računa ni mogoče, ko ste prijavljeni. Prosimo odjavite se in poskusite ponovno.";
$_lang["successfully.registered"] = "Registracija je uspešna. Prosimo preverite vašo e-pošto in aktivirajte račun.";
$_lang["error.unknown"] = "Neznana napaka";
$_lang["credentials.taken"] = "Uporabniško ime, e-naslov ali steamID je že v uporabi.";
$_lang["error.no.steam.data"] = "Za ustvaritev vašega ETS2MP računa mora biti igra ETS2 na voljo na vašem Steam računu. Če je igra na voljo v vaši Steam knjižnici, preverite če je vaš profil javen. Če je vaš profil zaseben, ga nastavite na javno in pritisnite";
$_lang["register.steam.info"] = "Za registracijo je potrebna prijava v Steam račun. Pritisnite na spodnji gumb za preusmeritev na stran za avtentikacijo vašega Steam računa.";
$_lang["rules.info"] = "Z registracijo avtomatsko sprejmete naša pravila skupnosti. Če si želite ogledati pravila, kliknite tukaj.";
$_lang["mail"] = "E-naslov";
$_lang["repeat.mail"] = "Ponovi e-naslov";
$_lang["new.password"] = "Novo geslo";
$_lang["repeat.new.password"] = "Ponovite novo geslo";
$_lang["new.password.summary"] = "Če pustite ta polja prazna, vaše geslo ne bo spremenjeno.";
$_lang["old.password"] = "Staro geslo";
$_lang["repeat.old.password"] = "Ponovite staro geslo";
$_lang["save.account.data"] = "Shrani podatke o računu";
$_lang["edit.account"] = "Uredi račun";
$_lang["forgot.password"] = "Pozabljeno geslo? Kliknite <a href=\"index.php?page=resetPassword\">tukaj</a>.";
$_lang["forgot.password.summary"] = "Ste pozabili geslo? Vpišite svoj e-naslov in pritisnite gumb \"Pozabljeno geslo\".";
$_lang["reminder.button"] = "Pozabljeno geslo";
$_lang["reset.password"] = "Ponastavi geslo";
$_lang["password.reminder.mail.title"] = "Pozabljeno geslo ETS2MP.";
$_lang["password.reminder.content"] = "Pozdravljeni.\n\nNekdo z IP {0}  je zahteval ponastavitev gesla za vaš ETS2MP račun.\n\nZa ponastavitev gesla sledite naslednji povezavi: {1}.\nČe to niste bili vi, prezrite sporočilo.\n\nLep pozdrav,\nEkipa ETS2MP";
$_lang["new.password.mail.title"] = "Vaše novo geslo.";
$_lang["new.password.mail.content"] = "Pozdravljeni.\n\nTo je vaše novo geslo: {0}\n\nSpremenite ga nemudoma po prijavi.\n\nLep pozdrav,\nEkipa ETS2MP";
$_lang["account.activated"] = "Vaš račun je bil uspešno akriviran.";
$_lang["unable.to.activate"] = "Aktivacija računa ni uspela, koda je neveljavna ali pa je račun že aktiviran.";
$_lang["not.activated"] = "Vaš račun še ni aktiviran. Če niste prejeli sporočila za aktivacijo kliknite <a href=\"index.php?action=resendActivation\">tukaj</a> in posredovali vam bomo nov aktivacijski ključ.";
$_lang["force.password.change"] = "Prosimo, da nemudoma spremenite geslo. Kliknite <a href=\"index.php?page=editAccount\">tukaj</a> za spremembo gesla.";
$_lang["forgot.password.link.sent"] = "Preverite vašo e-pošto. Poslali smo vam povezavo za ponastavitev gesla.";
$_lang["forgot.password.sent"] = "Preverite vašo e-pošto. Poslali smo vam novo geslo.";
$_lang["forgot.password.invalid.key"] = "Neveljavni ključ za ponastavitev gesla.";
$_lang["activation.key.resent"] = "Nov aktivacijski ključ je bil poslan na vaš e-naslov.";
$_lang["activation.mail.title"] = "Aktivacija ETS2MP računa.";
$_lang["activation.mail.content"] = "Pozdravljeni.\n\nTo je vaš aktivacijski ključ: {0}\n\nLep pozdrav,\nEkipa ETS2MP";
$_lang["no.login"] = "Za vstop na stran je potrebna prijava.";
$_lang["settings.saved.with.mail"] = "Račun je bil shranjen. Preverite vašo e-pošto in ponovno aktivirajte račun.";
$_lang["new.email.in.use"] = "Ta e-naslov je že v uporabi.";
$_lang["email.does.not.match"] = "Vnesena e-naslova se ne ujemata.";
$_lang["invalid.email.format"] = "Vneseni e-naslov ni veljaven.";
$_lang["new.password.does.not.match"] = "Novo vneseno geslo se ne ujema.";
$_lang["too.short.password"] = "Geslo je prekratko. Minimum 5 znakov";
$_lang["old.password.does.not.match"] = "Staro geslo se ne ujema.";
$_lang["settings.saved"] = "Račun je bil shranjen.";
$_lang["invalid.old.password"] = "Staro geslo je nevejlavno, nastavitev ni mogoče shraniti.";
$_lang["no.password.change.forced"] = "Za ponastavitev gesla se je potrebno odjaviti.";
$_lang["password.reminder.edit.account"] = "Pozabljeno geslo? Kliknite <a href=\"index.php?page=resetPassword\">tukaj</a>.";
$_lang["contact"] = "Kontakt";
$_lang["your.mail"] = "Vaš e-naslov";
$_lang["content"] = "Vsebina";
$_lang["send"] = "Pošlji";
$_lang["contact.message.sent"] = "Hvala, ker ste nas kontaktirali. Prosimo počakajte na odgovor.";
$_lang["topic"] = "Tema";
$_lang["contact.message.too.short"] = "Sporočilo je prekratko. Minimum 10 znakov.";
$_lang["contact.topic.too.short"] = "Tema je prekratka. Minimum 10 znakov.";
$_lang["invalid.mail.forgot.password"] = "Račun, ki je povezan s tem naslovom, ni mogoče najti.";
$_lang["steamid.in.use"] = "Našli smo ETS2MP račun, ki je že povezan s tem Steam računom. Če ste naleteli na težave z registracijo <a href=\"http://ets2mp.com/support/\">pošljite vaše vprašanje</a>.";
$_lang["mail.does.not.match"] = "Vstavljeni e-naslov se ne ujema.";
$_lang["support"] = "Pomoč uporabnikom";
$_lang["profile"] = "Profil";
$_lang["group"] = "Skupina";
$_lang["banned"] = "Izključeni";
$_lang["state"] = "Status";
$_lang["account.is.activated"] = "Račun je aktiviran";
$_lang["account.isnt.activated"] = "Račun ni aktiviran";
$_lang["penalty.history"] = "Zgodovina kazni";
$_lang["no.punishments"] = "Ni kazni za prikaz.";
$_lang["date"] = "Datum";
$_lang["reason"] = "Razlog";
$_lang["type"] = "Tip";
$_lang["penalty.limit"] = "Samo lastnik tega računa lahko pregleduje daljšo zgodovino kazni.";
